const data = {
  products: [
    {
      name: "Free Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: "Smart shirt",
    },
    {
      name: "Shirt+",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 10,
      brand: "Nike",
      rating: 4.0,
      numReviews: 9,
      countInStock: 10,
      description: "A popular shirt",
    },
  ],
};
